---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Impact of German Sampling Protocol on Condition Modelling

```{r, message=F, include=F}
direct <- "Y:/Offshore scallop/Assessment/"
mwger <- read.csv(paste0(direct, "Data/Survey_data/2018/Spring/Ger/mw_Data.csv"))
mwger_0 <- read.csv(paste0(direct, "Data/Survey_data/2018/Spring/Ger/mw_Data_inclCommercial.csv"))

shfger <- read.csv(paste0(direct, "Data/Survey_data/2018/Spring/Ger/Survey1985-2018.csv"))
shfger_0 <- read.csv(paste0(direct, "Data/Survey_data/2018/Spring/Ger/Survey1985-2018_inclCommercial.csv"))

load("C:/Documents/Offshore scallop/Assessment/Data/Survey_data/2018/Survey_summary_output/testing_results_GermanSurveyOnly.RData")
HtWt.fit <- cf.data$Ger$HtWt.fit

load("C:/Documents/Offshore scallop/Assessment/Data/Survey_data/2018/Survey_summary_output/testing_results_GermanInclCommercial.RData")
HtWt.fit_0 <- cf.data$Ger$HtWt.fit

direct = "C:/Documents/Offshore scallop/Assessment/"

require(ggplot2)
require(plyr)
require(dplyr)
require(reshape2)
require(pander)
require(lme4)
require(grid)
require(gridExtra)
require(sp)
require(rgdal)
require(maptools)
require(raster)
require(rgeos)
require(fields)

```

```{r, include=F, warning=F, message=F}
### create multiple versions of the CF-TS figure with different subsets of data
### this requires models with different data subsets
testplot <- function(mwdat) {
  source("C:/Documents/Offshore scallop/Assessment/Assessment_fns/Survey_and_OSAC/shwt.lme.r")
  source("C:/Documents/Offshore scallop/Assessment/Assessment_fns/Survey_and_OSAC/condFac.R")
  source("C:/Documents/Offshore scallop/Assessment/Assessment_fns/Survey_and_OSAC/shwt.plt1.R")
  source("C:/Documents/Offshore scallop/Assessment/Assessment_fns/Survey_and_OSAC/stdts.plt.R")

  mwdat$ID <- as.character(mwdat$ID)
  condmod <- condFac(mwdat, shfger, model.type="glm", dirct=direct, error=T) 
  
  mwdat$sh <- mwdat$sh/100

  mwshmod <- shwt.lme(mwdat, random.effect='ID', b.par=3, verbose = T)
    condmod$CFyrs <- join(condmod$CFyrs, data.frame(year=1985:2018), type="right")
    
  cf.lab <-expression(paste("CF:",bgroup("(",frac(g,dm^3)   ,")")))
  
  par(mfrow=c(1,2))
  shwt.plt1(mwshmod,lw=3,ht=10,wd=12,cx=1.5,cex.mn = 2,las=1, titl = "MW-SH Relationship (Ger-2018)", axis.cx = 1, yl=c(0,90), xl=c(.60,1.90))
  stdts.plt(condmod$CFyrs,y=c('CF'),pch=c(23),col=c('blue'),ylab=cf.lab,
            mean.line=T,graphic='none',xlab='Year',ylim=c(4,25),las=1,
            titl = "Condition factor time series (Ger)",cex.mn=2,tx.ypos=4, error=T)

  list(mwshmod=mwshmod, condmod=condmod)

}

full <- testplot(mwger)
old <- testplot(mwger[mwger$year<2008,])
new <- testplot(mwger[mwger$year>2007,])
big <- testplot(mwger[mwger$sh>89,])
big_new <- testplot(mwger[mwger$sh>89 & mwger$year>2009,])
```

### Change in MWSH relationship
```{r, message=F, warning=F, echo=F}
MWSH_temp <- rbind(
      data.frame(old$mwshmod$data, pred=old$mwshmod$data$sh^old$mwshmod$B * old$mwshmod$A, run="old"), 
      data.frame(new$mwshmod$data, pred=new$mwshmod$data$sh^new$mwshmod$B * new$mwshmod$A, run="new"))

MWSH_size <- rbind(
      data.frame(big$mwshmod$data, pred=big$mwshmod$data$sh^big$mwshmod$B * big$mwshmod$A, run="big"),
      data.frame(big_new$mwshmod$data, pred=big_new$mwshmod$data$sh^big_new$mwshmod$B * big_new$mwshmod$A, run="big_new"),
      data.frame(old$mwshmod$data, pred=old$mwshmod$data$sh^old$mwshmod$B * old$mwshmod$A, run="old"), 
      data.frame(new$mwshmod$data, pred=new$mwshmod$data$sh^new$mwshmod$B * new$mwshmod$A, run="new"))

png(paste0(direct, "/2019/Presentations/Special_industry_presentations/MWSH shift_temp.png"), height=6, width=6, units="in", res=490)
ggplot() + geom_line(data=MWSH_temp, aes(sh*100, pred, colour=run, linetype=run)) +
  theme_bw() + theme(panel.grid=element_blank())+
  ylab("Meat Weight (g)") +
  xlab("Shell Height (mm)") +
  scale_colour_manual(name="Time series", labels=c("\nBefore 2008\n(unlined gear)\n", "2008+\n(lined gear)"), values=c("black", "blue")) +
  scale_linetype_discrete(name="Time series", labels=c("\nBefore 2008\n(unlined gear)\n", "2008+\n(lined gear)"))
dev.off() 

png(paste0(direct, "/2019/Presentations/Special_industry_presentations/MWSH shift_size.png"), height=6, width=6, units="in", res=490)
ggplot() + geom_line(data=MWSH_size[MWSH_size$run %in% c("big", "big_new"),], aes(sh*100, pred, colour=run, linetype=run)) +
  theme_bw() + theme(panel.grid=element_blank())+
   ylab("Meat Weight (g)") +
  xlab("Shell Height (mm)") +
  scale_colour_manual(name="Data group", labels=c("\n>89, all years\n", ">89, 2008+"), values=c("black", "blue")) +
  scale_linetype_discrete(name="Data group", labels=c("\n>89, all years\n", ">89, 2008+"))
dev.off()

png(paste0(direct, "/2019/Presentations/Special_industry_presentations/MWSH shift_size_temp.png"), height=6, width=6, units="in", res=490)
ggplot() + geom_line(data=MWSH_size[!MWSH_size$run %in% c("big_new"),], aes(sh*100, pred, colour=run, linetype=run)) +
  theme_bw() + theme(panel.grid=element_blank())+
   ylab("Meat Weight (g)") +
  xlab("Shell Height (mm)") +
  scale_colour_manual(name="Data group", labels=c("\n>89mm, all years\n", "\nBefore 2008\n(unlined gear)\n", "2008+\n(lined gear)\n"), values=c("black", "blue", "red")) +
  scale_linetype_discrete(name="Data group", labels=c("\n>89mm, all years\n", "\nBefore 2008\n(unlined gear)\n", "2008+\n(lined gear)\n"))
dev.off()

```

### Change in condition model estimate error through time
```{r, message=F,warning=F,  echo=F}
CFyrs_temp <- rbind(#data.frame(full$condmod$CFyrs, run="full"), 
      data.frame(old$condmod$CFyrs, run="old"), 
      data.frame(new$condmod$CFyrs, run="new")#, 
      #data.frame(big$condmod$CFyrs, run="big"), 
      #data.frame(big_new$condmod$CFyrs, run="big_new")
      )

CFyrs_size <- rbind(#data.frame(full$condmod$CFyrs, run="full"), 
      #data.frame(old$condmod$CFyrs, run="old"), 
      #data.frame(new$condmod$CFyrs, run="new")#, 
      data.frame(big$condmod$CFyrs, run="big"), 
      data.frame(big_new$condmod$CFyrs, run="big_new"))

png(paste0(direct, "/2019/Presentations/Special_industry_presentations/Precision ts.png"), height=6, width=8.5, units="in", res=490)
ggplot() + geom_point(data=CFyrs_temp, aes(year, CFse.fit, colour=run, shape=run)) +
  geom_line(data=CFyrs_temp, aes(year, CFse.fit, colour=run)) +
  theme_bw() + theme(panel.grid = element_blank())+
  geom_smooth(data=CFyrs_temp, aes(year, CFse.fit), method="lm", colour="black", lty="dashed", se=F) +
  ylab("Estimate error") +
  xlab("Year") +
  scale_colour_manual(name="Time series", labels=c("\nBefore 2008\n(unlined gear)\n", "2008+\n(lined gear)"), values=c("blue", "red"))+
  scale_shape_discrete(name="Time series", labels=c("\nBefore 2008\n(unlined gear)\n", "2008+\n(lined gear)"))
dev.off()
```

### What if we pretend that we kept using unlined gear? 
```{r, echo=F, message=F, warning=F, fig.width=15, fig.height=8}
png(paste0(direct, "/2019/Presentations/Special_industry_presentations/MWSH_above89mm.png"), width = 13,height = 8.5,res=420, units="in")
cf.lab <-expression(paste("CF:",bgroup("(",frac(g,dm^3)   ,")")))
par(mfrow=c(1,2))
shwt.plt1(big_new$mwshmod,lw=3,ht=10,wd=12,cx=1.5,cex.mn = 2,las=1, titl = "MW-SH Relationship (Ger-2018)", axis.cx = 1, yl=c(0,90), xl=c(.60,1.90))
stdts.plt(big_new$condmod$CFyrs,y=c('CF'),pch=c(23),col=c('blue'),ylab=cf.lab,
          mean.line=T,graphic='none',xlab='Year',ylim=c(4,25),las=1,
          titl = "Condition factor time series (Ger)",cex.mn=2,tx.ypos=4, error=T)
dev.off()
```

