--- 
title: "Offshore Scallop Survey Summary"
subtitle: "Spring 2022"
author: "Scallop and Benthic Habitat Unit"
output: 
  bookdown::pdf_document2:
    extra_dependencies: ["float"]
    toc: yes
    toc_depth: 1
header-includes:
 - \usepackage{float}
 - \usepackage{fancyhdr}
 - \pagestyle{fancy}
 - \fancyfoot[CO,CE]{Spring Survey 2022}
 - \fancyfoot[LE,RO]{\thepage}
---

```{r, echo=F, message=F, warning=F}
require(lubridate)
load("summary.Rdata")

dates <- summary_data$dates[summary_data$dates$bank %in% c("Mid", "Sab", "Ger",
          "BBn", "GB"),]
```

 
\newpage


# Survey overview

The Spring Offshore Scallop Survey occurred from `r stamp("March 1")(min(dates$start)-days(1))` to `r stamp("March 1, 2021")(max(dates$end))` on Middle Bank, Sable Bank, German Bank, Browns Bank North, Browns Bank South, and the Georges Bank monitoring stations. The Chief Scientist was Tricia Pearo Drew, and the survey was carried out on the Fundy Leader.

This report summarizes the information collected during the survey. At each survey station, the 8-ft scallop dredge is towed for 10 minutes, and all sea scallops are counted and assigned to 5mm shell height bins (ranging from 0-200mm). This information informs the abundance time series, shell height frequency, clapper time series, and spatial distribution figures. 

Detailed sampling occurred at a selection of the stations, where the exact shell heights and meat weights are recorded for a subsample of the scallops caught. This allows for the calculation of biomass and condition that are presented in the biomass time series, meat weight-shell height relationship, and condition time series figures. 

Some of the figures and analyses presented in this report refer to the different size classes of scallop: pre-recruits, recruits, and fully-recruited scallops. The shell height ranges for each size class differs by bank, but the general convention is that recruits are expected to grow to commercial size in the next year, while fully-recruited scallops were commercial size at the time of the survey. 

We also compare values from the current survey to the most recent previous survey, and/or to long term medians. In this report, all long term medians exclude the value from the current year. 

Trials of Olex navigational software continued during this 2021 survey. All tows on all banks were tracked using Olex software, and tows on German, Browns (North and South), and Georges Banks were also tracked using OceanVision software. A conversion factor was developed to ensure Olex tow tracks were comparable with OceanVision tow tracks. For Middle and Sable Banks, Olex tow tracks were used to calculate the distance coefficients needed to standardize tow lengths. 

In 2022, before the Spring Survey occurred, all historical survey data were loaded to the DFO SCALOFF database following the completion of a comprehensive data review. During the review, data or code related to tow numbering, tow locations, tow types, and dates were corrected as needed. For the majority of banks and years, these corrections had no impact on survey indices. The following corrections had minor impacts on survey summary results for the figures noted: 

-  Middle Bank: 12 tows in 1985, 1987, and 1989 were moved to Banquereau (Figures 2, 3, 5 and 11)    
-  Sable Bank: 6 tows of survey data in 1999 were recovered and included in analyses; 1 tow from 1992 was excluded (Figures 14, 15, 17 and 23)    
-  Georges Bank monitoring stations: Depth information was recovered for one sampled tow in 1988, which enabled condition factor to be calculated for that year (Figures 51 and 53)     
