--- 
title: "Offshore Scallop Survey Summary"
subtitle: "Spring & Summer 2024"
author: "Scallop and Benthic Habitat Unit"
output: 
  officedown::rdocx_document
editor_options: 
  chunk_output_type: console
---

```{r, echo=F, message=F, warning=F}
require(lubridate)
load("summary4.Rdata")

dates <- summary_data$dates[summary_data$dates$bank %in% c("Mid", "Sab", "Ger",
          "BBn", "GB", "GBa", "GBb"),]
```


# Survey overview

The Offshore Scallop Surveys in `r year` occurred on Middle Bank, Sable Bank, German Bank, Browns Bank North and the Georges Bank monitoring stations in the Spring, and Georges Bank 'a' and Georges Bank 'b' in the Summer. The Chief Scientist was Tricia Pearo Drew, and the surveys were carried out on the Fundy Leader.

This report summarizes the information collected during the survey. At each survey station, the 8-ft scallop dredge is towed for 10 minutes, and scallop are counted and assigned to 5mm shell height bins (ranging from 0-200mm). This information informs the abundance time series, shell height frequency, clapper time series, and spatial distribution figures. 

Detailed sampling occurred at a selection of the stations, where the exact heights and weights are recorded for a subsample of the scallops caught. This allows for the calculation of biomass and condition that are presented in the biomass time series, meat weight-shell height relationship, and condition time series figures. 

Some of the figures and analyses presented in this report refer to the different size classes of scallop: pre-recruits, recruits, and fully-recruited scallop. The shell height ranges for each size class differs by bank, but the general convention is that recruits are expected to grow to commercial size in the next year, while fully-recruited scallops were commercial size at the time of the survey. 


