## A quick script to look at the survey catches over time for each bank, + 


#load(paste(direct,"Data/Survey_data/",yr,"/Survey_summary_output/Survey_all_results.Rdata",sep=""))  
#load(paste(direct,"Data/Survey_data/",yr,"/Survey_summary_output/Survey_preprocessed.Rdata",sep="")) 

# Here's a quick plot of the total number of scallops caught each year for a given bank...
bbn.tot <- aggregate(tot ~ year,surv.Live$BBn,FUN=sum)
bbs.tot <- aggregate(tot ~ year,surv.Live$BBs,FUN=sum)
ger.tot <- aggregate(tot ~ year,surv.Live$Ger,FUN=sum)
sab.tot <- aggregate(tot ~ year,surv.Live$Sab,FUN=sum)
gba.tot<- aggregate(tot ~ year,surv.Live$GBa,FUN=sum)
gbb.tot<- aggregate(tot ~ year,surv.Live$GBb,FUN=sum)
gbspring.tot<- aggregate(tot ~ year,surv.Live$GB,FUN=sum)
mid.tot<- aggregate(tot ~ year,surv.Live$Mid,FUN=sum)
windows(15,8)
par(mfrow=c(2,4),mar=c(2,6,2,0))
plot(gba.tot$tot~gba.tot$year,type="o",log='y',main="GBa",ylab="",xlab="",ylim=c(800,5e5),las=1,bty="L")
mtext(side=2,"Total Number",line = 4)
plot(gbb.tot$tot~gba.tot$year,type="o",log='y',main="GBb",xlab="",ylab="",ylim=c(800,5e5),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(gbspring.tot$tot~gbspring.tot$year,type="o",log='y',main="GB Spring",xlab="",ylab="",ylim=c(800,5e5),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(bbn.tot$tot~bbn.tot$year,type="o",log='y',main="BBn",xlab="",ylab="",ylim=c(800,5e5),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(bbs.tot$tot~bbs.tot$year,type="o",log='y',main="BBs",ylab="",xlab="",ylim=c(100,30000),las=1,bty="L")
mtext(side=2,"Total Number",line = 4)
plot(ger.tot$tot~ger.tot$year,type="o",log='y',main="Ger",xlab="",ylab="",ylim=c(100,30000),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(sab.tot$tot~sab.tot$year,type="o",log='y',main="Sab",xlab="",ylab="",ylim=c(100,30000),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(mid.tot$tot~mid.tot$year,type="o",log='y',main="Mid",xlab="",ylab="",ylim=c(100,30000),las=1,yaxt="n",bty="L")
axis(2,labels=NA)

# Here's a quick plot of the total number of commercial sized scallops caught each year for a given bank...
bbn.com <- aggregate(com ~ year,surv.Live$BBn,FUN=sum)
bbs.com <- aggregate(com ~ year,surv.Live$BBs,FUN=sum)
ger.com <- aggregate(com ~ year,surv.Live$Ger,FUN=sum)
sab.com <- aggregate(com ~ year,surv.Live$Sab,FUN=sum)
gba.com<- aggregate(com ~ year,surv.Live$GBa,FUN=sum)
gbb.com<- aggregate(com ~ year,surv.Live$GBb,FUN=sum)
gbspring.com<- aggregate(com ~ year,surv.Live$GB,FUN=sum)
mid.com<- aggregate(com ~ year,surv.Live$Mid,FUN=sum)
windows(15,8)
par(mfrow=c(2,4),mar=c(2,6,2,0))
plot(gba.com$com~gba.com$year,type="o",log='y',main="GBa",ylab="",xlab="",ylim=c(200,5e4),las=1,bty="L")
mtext(side=2,"Fully Recruited",line = 4)
plot(gbb.com$com~gba.com$year,type="o",log='y',main="GBb",xlab="",ylab="",ylim=c(200,5e4),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(gbspring.com$com~gbspring.com$year,type="o",log='y',main="GB Spring",xlab="",ylab="",ylim=c(200,5e4),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(bbn.com$com~bbn.com$year,type="o",log='y',main="BBn",xlab="",ylab="",ylim=c(200,5e4),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(bbs.com$com~bbs.com$year,type="o",log='y',main="BBs",ylab="",xlab="",ylim=c(50,10000),las=1,bty="L")
mtext(side=2,"Fully Recruited",line = 4)
plot(ger.com$com~ger.com$year,type="o",log='y',main="Ger",xlab="",ylab="",ylim=c(50,10000),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(sab.com$com~sab.com$year,type="o",log='y',main="Sab",xlab="",ylab="",ylim=c(50,10000),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(mid.com$com~mid.com$year,type="o",log='y',main="Mid",xlab="",ylab="",ylim=c(50,10000),las=1,yaxt="n",bty="L")
axis(2,labels=NA)


bbn.tot.mn <- aggregate(tot ~ year,surv.Live$BBn,FUN=mean)
bbs.tot.mn <- aggregate(tot ~ year,surv.Live$BBs,FUN=mean)
ger.tot.mn <- aggregate(tot ~ year,surv.Live$Ger,FUN=mean)
sab.tot.mn <- aggregate(tot ~ year,surv.Live$Sab,FUN=mean)
gba.tot.mn<- aggregate(tot ~ year,surv.Live$GBa,FUN=mean)
gbb.tot.mn<- aggregate(tot ~ year,surv.Live$GBb,FUN=mean)
gbspring.tot.mn<- aggregate(tot ~ year,surv.Live$GB,FUN=mean)
mid.tot.mn<- aggregate(tot ~ year,surv.Live$Mid,FUN=mean)
windows(15,8)
par(mfrow=c(2,4),mar=c(2,6,2,0))
plot(gba.tot.mn$tot~gba.tot.mn$year,type="o",log='y',main="GBa",ylab="",xlab="",ylim=c(100,20000),las=1,bty="L")
mtext(side=2,"Total Number",line = 4)
plot(gbb.tot.mn$tot~gba.tot.mn$year,type="o",log='y',main="GBb",xlab="",ylab="",ylim=c(100,20000),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(gbspring.tot.mn$tot~gbspring.tot.mn$year,type="o",log='y',main="GB Spring",xlab="",ylab="",ylim=c(100,20000),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(bbn.tot.mn$tot~bbn.tot.mn$year,type="o",log='y',main="BBn",xlab="",ylab="",ylim=c(100,20000),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(bbs.tot.mn$tot~bbs.tot.mn$year,type="o",log='y',main="BBs",ylab="",xlab="",ylim=c(10,5000),las=1,bty="L")
mtext(side=2,"Total Number",line = 4)
plot(ger.tot.mn$tot~ger.tot.mn$year,type="o",log='y',main="Ger",xlab="",ylab="",ylim=c(10,5000),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(sab.tot.mn$tot~sab.tot.mn$year,type="o",log='y',main="Sab",xlab="",ylab="",ylim=c(10,5000),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(mid.tot.mn$tot~mid.tot.mn$year,type="o",log='y',main="Mid",xlab="",ylab="",ylim=c(10,5000),las=1,yaxt="n",bty="L")
axis(2,labels=NA)

# Here's a quick plot of the total number of commercial sized scallops caught each year for a given bank...
bbn.com.mn <- aggregate(com ~ year,surv.Live$BBn,FUN=mean)
bbs.com.mn <- aggregate(com ~ year,surv.Live$BBs,FUN=mean)
ger.com.mn <- aggregate(com ~ year,surv.Live$Ger,FUN=mean)
sab.com.mn <- aggregate(com ~ year,surv.Live$Sab,FUN=mean)
gba.com.mn<- aggregate(com ~ year,surv.Live$GBa,FUN=mean)
gbb.com.mn<- aggregate(com ~ year,surv.Live$GBb,FUN=mean)
gbspring.com.mn<- aggregate(com ~ year,surv.Live$GB,FUN=mean)
mid.com.mn<- aggregate(com ~ year,surv.Live$Mid,FUN=mean)
windows(15,8)
par(mfrow=c(2,4),mar=c(2,6,2,0))
plot(gba.com.mn$com~gba.com.mn$year,type="o",log='y',main="GBa",ylab="",xlab="",ylim=c(10,7e2),las=1,bty="L")
mtext(side=2,"Fully Recruited",line = 4)
plot(gbb.com.mn$com~gba.com.mn$year,type="o",log='y',main="GBb",xlab="",ylab="",ylim=c(10,7e2),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(gbspring.com.mn$com~gbspring.com.mn$year,type="o",log='y',main="GB Spring",xlab="",ylab="",ylim=c(10,7e2),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(bbn.com.mn$com~bbn.com.mn$year,type="o",log='y',main="BBn",xlab="",ylab="",ylim=c(10,7e2),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(bbs.com.mn$com~bbs.com.mn$year,type="o",log='y',main="BBs",ylab="",xlab="",ylim=c(5,500),las=1,bty="L")
mtext(side=2,"Fully Recruited",line = 4)
plot(ger.com.mn$com~ger.com.mn$year,type="o",log='y',main="Ger",xlab="",ylab="",ylim=c(5,500),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(sab.com.mn$com~sab.com.mn$year,type="o",log='y',main="Sab",xlab="",ylab="",ylim=c(5,500),las=1,yaxt="n",bty="L")
axis(2,labels=NA)
plot(mid.com.mn$com~mid.com.mn$year,type="o",log='y',main="Mid",xlab="",ylab="",ylim=c(5,500),las=1,yaxt="n",bty="L")
axis(2,labels=NA)


# Here's a summary of all the tow types on GBa and BBn ever...

GBa.tows <- aggregate(tot~random+year,surv.Live$GBa,FUN=length)
GBa.extras <- GBa.tows[GBa.tows$random !=1,]
GBa.reg <- GBa.tows[GBa.tows$random ==1,]
BBn.tows <- aggregate(tot~random+year,surv.Live$BBn,FUN=length)
BBn.extras <- BBn.tows[BBn.tows$random !=1,]
BBn.reg <- BBn.tows[BBn.tows$random ==1,]

windows(11,11)
par(mfrow=c(2,2),mar=c(2,6,2,0))
plot(GBa.extras$tot ~ GBa.extras$year,type="p",pch=19,ylim=c(0,50),ylab="Non-regular tows",xlab="",main="GBa")
plot(BBn.extras$tot ~ BBn.extras$year,type="p",pch=19,ylim=c(0,50),ylab="Non-regular tows",xlab="",main="BBn")
plot(GBa.reg$tot ~ GBa.reg$year,type="p",pch=19,ylim=c(0,200),ylab="Regular tows",xlab="",main="GBa")
plot(BBn.reg$tot ~ BBn.reg$year,type="p",pch=19,ylim=c(0,200),ylab="Regular tows",xlab="",main="BBn")
