---
title: "Spatial data checks for 2024 survey"
editor_options:
  chunk_output_type: console
output:
  html_document:
    df_print: paged
classoption: landscape
---

```{r, include=F, echo=F, message=F, warning=F}
direct_fns <- "C:/Users/keyserf/Documents/Github/Assessment_fns/"
direct_data <- "Y:/Offshore/Assessment/"
bank <- "GBb" # to do: Sab, GBa, GBb
year <- 2024 # this is for the folder save location
survey_years <- 2023 # choose one year only (most recent will contain past years)
fishery_years <- 2022:2023 # choose multiple years. must be a year in which fishing occurred
station_years <- 2024
seeds=10304:10308

# TIPS: run all banks that were surveyed in the previous year first. Then change survey_years to match the year for the most recent survey of any banks that were not surveyed in the previous year (e.g. BBs, Ban), and re-run offshore_data for each of those. 

require(dplyr)
require(patchwork)

source(paste0(direct_fns, "Maps/plot_offshore_spatial.R"))
source(paste0(direct_fns, "Maps/pectinid_projector_sf.R"))

#load the data
offshore_data <- load_offshore_spatial(direct_data=direct_data,
                                       direct_fns = direct_fns,
                                       survey=T,
                                       fishery=T,
                                       survey_year=survey_years,
                                       fishery_years=fishery_years, 
                                       detailedsampling=T)
```

```{r, echo=F, message=F, warning=F, include=F}
# make the figs
plots <- function(seed){
  
  # survey
  png(paste0(direct_data, "/", year, "/Survey_Design/", bank, "/", seed, "/survey1.png"), height=6, width=12, units="in", res=400)
  #plots stations against most recent survey results
  survey1 <- plot_offshore_spatial(direct_data=direct_data,
                                   direct_fns = direct_fns,
                                   offshore_data=offshore_data,
                                   overlay_data="survey",
                                   survey_years=survey_years,
                                   station_years=station_years,
                                   size_class=NULL,
                                   seed=seed,
                                   bank=bank)
  print(survey1)
  dev.off()

  png(paste0(direct_data, "/", year, "/Survey_Design/", bank, "/", seed, "/survey2.png"), height=6, width=12, units="in", res=400)
  # plots stations against previous year survey results (2 years prior)
  survey2 <- plot_offshore_spatial(direct_data=direct_data,
                                   direct_fns = direct_fns,
                                   offshore_data=offshore_data,
                                   overlay_data="survey",
                                   survey_years=survey_years-1,
                                   station_years=station_years,
                                   size_class=NULL,
                                   seed=seed,
                                   bank=bank)
  print(survey2)
  dev.off()

  png(paste0(direct_data, "/", year, "/Survey_Design/", bank, "/", seed, "/survey3.png"), height=6, width=12, units="in", res=400)
  survey3 <- plot_offshore_spatial(direct_data=direct_data,
                                   direct_fns = direct_fns,
                                   offshore_data=offshore_data,
                                   overlay_data="survey",
                                   survey_years=survey_years-2,
                                   station_years=station_years,
                                   size_class=NULL,
                                   seed=seed,
                                   bank=bank)
  print(survey3)
  dev.off()
  
  
  surveytot <- plot_offshore_spatial(direct_data=direct_data,
                                   direct_fns = direct_fns,
                                   offshore_data=offshore_data,
                                   overlay_data="survey",
                                   survey_years=survey_years,
                                   station_years=station_years,
                                   size_class="tot",
                                   seed=seed,
                                   bank=bank)
  
  # fishery
  png(paste0(direct_data,  "/", year, "/Survey_Design/", bank, "/", seed, "/fishery.png"), height=6, width=12, units="in", res=400)
  # plots stations against all fishery data, facetted by year
  fishery <- plot_offshore_spatial(direct_data=direct_data,
                                   direct_fns = direct_fns,
                                   offshore_data=offshore_data,
                                   overlay_data="fishery",
                                   survey_years=survey_years,
                                   station_years=station_years,
                                   size_class=NULL,
                                   seed=seed,
                                   bank=bank)
  print(fishery)
  dev.off()

  
  return(list(surveytot, fishery))
}  

#apply the plotting function (above) to all seeds
output <- lapply(X = seeds, function(x) plots(x))

# Last year's survey, all seeds
png(paste0(direct_data, "/", year, "/Survey_Design/", bank, "/comparing_designs_w_survey.png"), height=8, width=16, units="in", res=400)
(output[[1]][[1]] + ggtitle(paste0("survey - ", seeds[1]))) +
  (output[[2]][[1]] + ggtitle(paste0("survey - ", seeds[2]))) +
  (output[[3]][[1]] + ggtitle(paste0("survey - ", seeds[3]))) +
  (output[[4]][[1]] + ggtitle(paste0("survey - ", seeds[4]))) +
  (output[[5]][[1]] + ggtitle(paste0("survey - ", seeds[5]))) + 
  # (output[[6]][[1]] + ggtitle(paste0("survey - ", seeds[6]))) + 
  # (output[[7]][[1]] + ggtitle(paste0("survey - ", seeds[7]))) +
  # (output[[8]][[1]] + ggtitle(paste0("survey - ", seeds[8]))) +
  plot_layout(guides = 'collect', nrow=2)
dev.off()


# Last year's fishery, all seeds
png(paste0(direct_data, "/", year, "/Survey_Design/", bank, "/comparing_designs_w_fishery.png"), height=8, width=16, units="in", res=400)
(output[[1]][[2]] + ggtitle(paste0("fishery - ", seeds[1]))) +
  (output[[2]][[2]] + ggtitle(paste0("fishery - ", seeds[2]))) +
  (output[[3]][[2]] + ggtitle(paste0("fishery - ", seeds[3]))) +
  (output[[4]][[2]] + ggtitle(paste0("fishery - ", seeds[4]))) +
  (output[[5]][[2]] + ggtitle(paste0("fishery - ", seeds[5]))) +
  # (output[[6]][[2]] + ggtitle(paste0("fishery - ", seeds[6]))) +
  # (output[[7]][[2]] + ggtitle(paste0("fishery - ", seeds[7]))) +
  # (output[[8]][[2]] + ggtitle(paste0("fishery - ", seeds[8]))) +
  plot_layout(guides = 'collect', nrow= 2)
dev.off()

```
